# Site settings
title: LE-V-EL
email: your-email@domain.com
description: >
  Provide standardized visualization benchmark datasets
  Rankings of computational methods for visualization understanding.
lang: en-US

baseurl: "/CS410-Prototype" # the subpath of your site, e.g. /blog/
url: https://woodylinwc.github.io/CS410-Prototype/ # the base hostname & protocol for your site
git_address: https://github.com/WoodyLinwc/CS410-Prototype
git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: America/New_York
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: submit
    seo:
      type: "WebPage"

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: links
    seo:
      type: "WebPage"

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

remote_theme: aksakalli/jekyll-doc-theme@gh-pages   
